/* generated by farmfe_plugin_react_components */
export {} 
declare global {
	const AgentInfoCard: typeof import('./src/components/AgentInfoCard')['default']
	const Main: typeof import('./src/pages/main')['Main']
}
