/* generated by farmfe_plugin_react_components */
export {} 
declare global {
	const Main: typeof import('./src/main')['Main']
	const AgentInfoCard: typeof import('./src/components/AgentInfoCard')['default']
}
